### PR TITLE
open_file2: hack-fix compilation with DEBUG_STATS

### PR DESCRIPTION
**Pull request by SergeGautherie**
`.../create.c:3485:9: error: 'open_type' undeclared (first use in this function)`

Broken since ab0a3d74e6b96c27b3dad4c7147d5117729f8ca5.

Feel free to commit an actual fix instead.

### CODE REVIEW

**Comment by SergeGautherie** [comment]
Should I add `open_type` as a parameter, as an actual fix?

**Comment by maharmstone** [comment]
Thanks Serge. I've gone ahead and removed the DEBUG_STATS code - it's served its purpose.
